### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by anbuhatakekakashi** [chrisjd20/node_ctf#1]
You pointed me here from your other project. But this doesn't work throws an error on run. When doing the "node app.js".

**Comment by chrisjd20** [comment]
Can you show me the error?

**Comment by chrisjd20** [comment]
I fixed some issues to help install. Basically you need to have mysql configured and put the db creds in the app.js file. 

Then simply run the following command when you are in the same directory:

npm install
node app.js

As long as you mysql server is on, it should work.

**Comment by anbuhatakekakashi** [comment]
Ah okay. I have tried the update yet. 
But here the errors I was getting before. 
One on clicking app.js
![error click](https://cloud.githubusercontent.com/assets/14054410/25152616/6e226064-243e-11e7-87ce-17abc15b6857.png)

one through cmd line
![error cmd](https://cloud.githubusercontent.com/assets/14054410/25152628/7877885a-243e-11e7-8109-584d963ce0d7.png)

**Comment by chrisjd20** [comment]
Follow the new installation instructions

#INSTALLATION

    git clone https://github.com/chrisjd20/node_ctf.git
    npm install
    Change values on lines 44-50 to reflect your system and db info
    node app.js <----- This starts the server

**Comment by anbuhatakekakashi** [comment]
Got it to run. But does seem to recognize admin/admin. 
![capture](https://cloud.githubusercontent.com/assets/14054410/25155685/450c4f34-244b-11e7-87dc-d2cfa3d86462.PNG)

And I can't register a new user. 

Lol, sorry for being a drag. You're probably like, "I have it working for me."

**Comment by chrisjd20** [comment]
It says error in connection to database. You need to make sure your MySQL db is on and your MySQL db is info is put into the app.js file. Modify lines in app.js 40-60 to reflect your systems information.

**Comment by anbuhatakekakashi** [comment]
Alright, I have tried everything. Even figured out MySQL Microsoft doesn't work that well. But fixed that issue. I'm still getting errors. What am I missing? You've gotten this to work right? 
![untitled](https://cloud.githubusercontent.com/assets/14054410/25316207/391bd4ea-2817-11e7-968c-53920afb6a35.png)

**Comment by chrisjd20** [comment]
It says your address is in use. That means there is already a service listening on your chosen socket.

**Comment by chrisjd20** [comment]
Check it out, I downloaded and unzipped the file or you could use git clone. 

Then I changed the appropriate lines for my database.

Then I just went into the directory and ran node app.js

![image](https://cloud.githubusercontent.com/assets/11812223/25316254/867729c8-2831-11e7-951f-a93e453bf225.png)


I tried this on linux too and had no problems:

![image](https://cloud.githubusercontent.com/assets/11812223/25316275/036c8b62-2832-11e7-9890-e29ab201ff54.png)

**Comment by anbuhatakekakashi** [comment]
Right. But earlier you stated to make sure your MySQL is on. By "on" I presume in a running state. If MySQL is listening on <insert> and your code is listening on the same port.  Doesn't work. I might be missing something in your instructions. If I turn off MySQL server. Yep. I get the same output as you. However, if I navigate to the page. I do get the login prompt. But the process isn't accepted. Because there is, obviously, no connection to the MySQL server. If I turn it on. I get the output, I just sent. I'm sorry for the headache. I feel like a dumb user, right now. But I have to be missing a step of your process.

**Comment by chrisjd20** [comment]
![image](https://cloud.githubusercontent.com/assets/11812223/25316384/440a772c-2834-11e7-8253-10db84ef25ea.png)

1. is the ip address of the mysql database. No need to put a mysql port unless mysql is listening  on a port other than 3306. If mysql is not listening on 3306 then you need to specify the hostname/ip and then : port number.... I.e.... 127.0.0.1:5555

2.  Your database username

3. Your database password

4. The Port you want the WEB (app.js) server to listen on. NOT the port number of mysql. Hence why it says httpport. Then you can view the website from any web browser via going to http://<ip address>:<specified port>/

**Comment by chrisjd20** [comment]
Actually, I need to correct myself for item number one. Instead of ip and port of your db host, you have to put in just the ip of the db host. and then change lines:
![image](https://cloud.githubusercontent.com/assets/11812223/25316475/dcfc5d8c-2835-11e7-8750-f2b58768b919.png)

You simply want to add an extra line to each of these that has your mysql port number on it. Would look something like:

port : 5555,


That should be it.

**Comment by anbuhatakekakashi** [comment]
That was it. Also point 4 was a  big misinterpretation on my part. And the clear on point 1 was good. Though, I would have just set my port back to default. Appreciate everything, and especially the quick replies.

**Comment by chrisjd20** [comment]
So there was a small bug that I just fixed that cause points not to be added up properly. 

![image](https://cloud.githubusercontent.com/assets/11812223/25540043/a36e7ab0-2c17-11e7-94ba-40a61cb97a22.png)


You will want to change the pointed out number to 2 instead of 1:
![image](https://cloud.githubusercontent.com/assets/11812223/25540067/bca2b1b8-2c17-11e7-9b70-d0529b0134ec.png)

**Comment by anbuhatakekakashi** [comment]
Ah okay. Thanks, I have given it a full testing yet. So would not have noticed.
