### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by iamzubin** [chrisjd20/node_ctf#2]
hey,
i am trying to use your platform to host a small ctf.
but while doing so. i'm not being able to figure out a lot of stuff.
for ex.
1. how to make another admin account
2. how to add  a trivia. (no UI??)

can you please document it a bit better.

**Comment by chrisjd20** [comment]
1. So this is a light-weight scoreboard so there is only one admin == "admin".
2. This is designed around hacking virtual machines by getting limited user access and then escalating to root or system access. As such, there are no trivia based questions. However, you could simply substitute limited and root answers to the answers for trivia that are in the questions themselves.
